// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int32
	UserID    int32
	Action    string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamp
}
