// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"database/sql"
)

type Post struct {
	ID        int64
	Title     string
	Content   string
	AuthorID  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
