version: '3'  

services:
  mysql:
    platform: linux/amd64
    image: 'mysql:8.1'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql:
